// Visit the wiki for more info - https://kubejs.com/
console.info('Heres the tags example script!')
ServerEvents.tags('item', event => {
    event.add('colossalchests:walls', [
        'colossalchests:chest_wall_wood',
        'colossalchests:chest_wall_copper',
        'colossalchests:chest_wall_silver',
        'colossalchests:chest_wall_iron',
        'colossalchests:chest_wall_gold',
        'colossalchests:chest_wall_diamond',
        'colossalchests:chest_wall_obsidian',
    ]);
    event.add('colossalchests:interfaces', [
        'colossalchests:interface_wood',
        'colossalchests:interface_copper',
        'colossalchests:interface_silver',
        'colossalchests:interface_iron',
        'colossalchests:interface_gold',
        'colossalchests:interface_diamond',
        'colossalchests:interface_obsidian',
      ]);
      event.add('colossalchests:cores', [
        'colossalchests:colossal_chest_wood',
        'colossalchests:colossal_chest_copper',
        'colossalchests:colossal_chest_silver',
        'colossalchests:colossal_chest_iron',
        'colossalchests:colossal_chest_gold',
        'colossalchests:colossal_chest_diamond',
        'colossalchests:colossal_chest_obsidian',
      ]);
      event.add('refinedstorage:processors', [
        'refinedstorage:basic_processor',
        'refinedstorage:improved_processor',
        'refinedstorage:advanced_processor',
      ]);
      event.add('refinedstorage:cores',[
        'refinedstorage:construction_core',
        'refinedstorage:destruction_core',
      ]);
      event.add('pipez:pipes',[
        'pipez:item_pipe',
        'pipez:fluid_pipe',
        'pipez:energy_pipe',
        'pipez:universal_pipe',
        'pipez:gas_pipe'
      ]);
      event.add('mekanism:cable_energy',[
        'mekanism:basic_universal_cable',
        'mekanism:advanced_universal_cable',
        'mekanism:elite_universal_cable',
        'mekanism:ultimate_universal_cable',
      ]);
      event.add('mekanism:cable_fluid',[
        'mekanism:basic_mechanical_pipe',
        'mekanism:advanced_mechanical_pipe',
        'mekanism:elite_mechanical_pipe',
        'mekanism:ultimate_mechanical_pipe',  
      ]);
      event.add('mekanism:cable_chemical',[
        'mekanism:basic_pressurized_tube',
        'mekanism:advanced_pressurized_tube',
        'mekanism:elite_pressurized_tube',
        'mekanism:ultimate_pressurized_tube',
      ]);
      event.add('mekanism:cable_heat',[
        'mekanism:basic_thermodynamic_conductor',
        'mekanism:advanced_thermodynamic_conductor',
        'mekanism:elite_thermodynamic_conductor',
        'mekanism:ultimate_thermodynamic_conductor',
      ]);
      event.add('mekanism:cable_others',[
        'mekanism:restrictive_transporter',
        'mekanism:diversion_transporter',
      ]);
      event.add('apothic_enchanting:tomes',[
        'apothic_enchanting:helmet_tome',
        'apothic_enchanting:chestplate_tome',
        'apothic_enchanting:leggings_tome',
        'apothic_enchanting:boots_tome',
        'apothic_enchanting:pickaxe_tome',
        'apothic_enchanting:weapon_tome',
        'apothic_enchanting:fishing_tome',
        'apothic_enchanting:bow_tome',
      ]);
      event.add('simplyswords:longswords',[
        'simplyswords:iron_longsword',
        'simplyswords:gold_longsword',
        'simplyswords:diamond_longsword',
        'simplyswords:netherite_longsword',
      ]);
      event.add('simplyswords:twinblades',[
        'simplyswords:iron_twinblade',
        'simplyswords:gold_twinblade',
        'simplyswords:diamond_twinblade',
        'simplyswords:netherite_twinblade',
      ]);
      event.add('simplyswords:rapiers',[
        'simplyswords:iron_rapier',
        'simplyswords:gold_rapier',
        'simplyswords:diamond_rapier',
        'simplyswords:netherite_rapier',
      ]);
      event.add('simplyswords:katanas',[
        'simplyswords:iron_katana',
        'simplyswords:gold_katana',
        'simplyswords:diamond_katana',
        'simplyswords:netherite_katana',
      ]);
      event.add('simplyswords:sais',[
        'simplyswords:iron_sai',
        'simplyswords:gold_sai',
        'simplyswords:diamond_sai',
        'simplyswords:netherite_sai',
      ]);
      event.add('simplyswords:spears',[
        'simplyswords:iron_spear',
        'simplyswords:gold_spear',
        'simplyswords:diamond_spear',
        'simplyswords:netherite_spear',
      ]);
      event.add('simplyswords:glaives',[
        'simplyswords:iron_glaive',
        'simplyswords:gold_glaive',
        'simplyswords:diamond_glaive',
        'simplyswords:netherite_glaive',
      ]);
      event.add('simplyswords:warglaives',[
        'simplyswords:iron_warglaive',
        'simplyswords:gold_warglaive',
        'simplyswords:diamond_warglaive',
        'simplyswords:netherite_warglaive',
      ]);
      event.add('simplyswords:cutlass',[
        'simplyswords:iron_cutlass',
        'simplyswords:gold_cutlass',
        'simplyswords:diamond_cutlass',
        'simplyswords:netherite_cutlass',
      ]);
      event.add('simplyswords:claymores',[
        'simplyswords:iron_claymore',
        'simplyswords:gold_claymore',
        'simplyswords:diamond_claymore',
        'simplyswords:netherite_claymore',
      ]);
      event.add('simplyswords:greathammers',[
        'simplyswords:iron_greathammer',
        'simplyswords:gold_greathammer',
        'simplyswords:diamond_greathammer',
        'simplyswords:netherite_greathammer',
      ]);
      event.add('simplyswords:greataxes',[
        'simplyswords:iron_greataxe',
        'simplyswords:gold_greataxe',
        'simplyswords:diamond_greataxe',
        'simplyswords:netherite_greataxe',
      ]);
      event.add('simplyswords:chakrams',[
        'simplyswords:iron_chakram',
        'simplyswords:gold_chakram',
        'simplyswords:diamond_chakram',
        'simplyswords:netherite_chakram',
      ]);
      event.add('simplyswords:scythes',[
        'simplyswords:iron_scythe',
        'simplyswords:gold_scythe',
        'simplyswords:diamond_scythe',
        'simplyswords:netherite_scythe',
      ]);
      event.add('simplyswords:halberds',[
        'simplyswords:iron_halberd',
        'simplyswords:gold_halberd',
        'simplyswords:diamond_halberd',
        'simplyswords:netherite_halberd',
      ]);
});
